# Generated by Django 5.1.1 on 2024-09-27 11:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='followed_users',
            field=models.ManyToManyField(related_name='followers_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
