# Generated by Django 5.1.1 on 2024-09-27 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_ticket_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFollows',
        ),
    ]
